server:
  port: 8001
spring:
  application:
    name: EMPLOYEE-PROVIDER
  datasource:
    url: jdbc:mysql://localhost:3306/xinyuan
    username: root
    password: shibun
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip

mybatis:
  type-aliases-package: ka.shibun.xinyuan.domain,ka.shibun.xinyuan.query
